Ext.define("net.nan21.dnet.module.fi.asset.ds.model.AssetDs$Trl", {
	
	calculation__lbl: "Calculation",
	categoryId__lbl: "Category(ID)",
	category__lbl: "Category",
	currencyId__lbl: "Currency(ID)",
	currency__lbl: "Currency",
	deprecEndDate__lbl: "Deprec End Date",
	deprecStartDate__lbl: "Deprec Start Date",
	depreciationAmount__lbl: "Depreciation Amount",
	initialDeprecAmount__lbl: "Initial Deprec Amount",
	initialValue__lbl: "Initial Value",
	method__lbl: "Method",
	orgId__lbl: "Org(ID)",
	org__lbl: "Org",
	periodPercenatge__lbl: "Period Percenatge",
	periodType__lbl: "Period Type",
	periodValue__lbl: "Period Value",
	productCode__lbl: "Product Code",
	productId__lbl: "Product(ID)",
	productName__lbl: "Product Name",
	purchaseDate__lbl: "Purchase Date",
	residualValue__lbl: "Residual Value",
	withDepreciation__lbl: "With Depreciation"
});
