Ext.define("net.nan21.dnet.module.sd.invoice.ds.model.SalesInvoiceDs$Trl", {
	
	billToContactId__lbl: "Bill To Contact(ID)",
	billToContact__lbl: "Bill To Contact",
	billToLocationId__lbl: "Bill To Location(ID)",
	billToLocation__lbl: "Bill To Location",
	businessObject__lbl: "Business Object",
	className__lbl: "Class Name",
	code__lbl: "Code",
	confirmed__lbl: "Confirmed",
	currencyId__lbl: "Currency(ID)",
	currency__lbl: "Currency",
	customerCode__lbl: "Customer Code",
	customerId__lbl: "Customer(ID)",
	customerUuid__lbl: "Customer(UUID)",
	customer__lbl: "Customer",
	description__lbl: "Description",
	docDate__lbl: "Doc Date",
	docNo__lbl: "Doc No",
	docTypeId__lbl: "Doc Type(ID)",
	docType__lbl: "Doc Type",
	paymentMethodId__lbl: "Payment Method(ID)",
	paymentMethod__lbl: "Payment Method",
	paymentTermId__lbl: "Payment Term(ID)",
	paymentTerm__lbl: "Payment Term",
	posted__lbl: "Posted",
	priceListId__lbl: "Price List(ID)",
	priceList__lbl: "Price List",
	salesOrderCode__lbl: "Sales Order Code",
	salesOrderId__lbl: "Sales Order(ID)",
	supplierId__lbl: "Supplier(ID)",
	supplier__lbl: "Supplier",
	totalAmount__lbl: "Total Amount",
	totalNetAmount__lbl: "Total Net Amount",
	totalTaxAmount__lbl: "Total Tax Amount"
});
