Ext.define("net.nan21.dnet.module.sd.order.ds.model.SalesDeliveryDs$Trl", {
	
	carrierId__lbl: "Carrier(ID)",
	carrier__lbl: "Carrier",
	code__lbl: "Code",
	confirmed__lbl: "Confirmed",
	customerCode__lbl: "Customer Code",
	customerId__lbl: "Customer(ID)",
	customer__lbl: "Customer",
	deliveryContactId__lbl: "Delivery Contact(ID)",
	deliveryContact__lbl: "Delivery Contact",
	deliveryLocationId__lbl: "Delivery Location(ID)",
	deliveryLocation__lbl: "Delivery Location",
	docDate__lbl: "Doc Date",
	docNo__lbl: "Doc No",
	eventDate__lbl: "Event Date",
	posted__lbl: "Posted",
	salesOrderId__lbl: "Sales Order(ID)",
	salesOrderUuid__lbl: "Sales Order(UUID)",
	salesOrder__lbl: "Sales Order",
	transactionTypeId__lbl: "Transaction Type(ID)",
	transactionType__lbl: "Transaction Type",
	warehouseId__lbl: "Warehouse(ID)",
	warehouse__lbl: "Warehouse"
});
