Ext.define("net.nan21.dnet.module.sd.order.ds.model.SalesOrderDs$Trl", {
	
	billToCode__lbl: "Bill To Code",
	billToContactId__lbl: "Bill To Contact(ID)",
	billToContact__lbl: "Bill To Contact",
	billToId__lbl: "Bill To(ID)",
	billToLocationId__lbl: "Bill To Location(ID)",
	billToLocation__lbl: "Bill To Location",
	billToUuid__lbl: "Bill To(UUID)",
	billTo__lbl: "Bill To",
	businessObject__lbl: "Business Object",
	carrierId__lbl: "Carrier(ID)",
	carrier__lbl: "Carrier",
	className__lbl: "Class Name",
	code__lbl: "Code",
	confirmed__lbl: "Confirmed",
	currencyId__lbl: "Currency(ID)",
	currency__lbl: "Currency",
	customerCode__lbl: "Customer Code",
	customerId__lbl: "Customer(ID)",
	customerUuid__lbl: "Customer(UUID)",
	customer__lbl: "Customer",
	delivDocTypeId__lbl: "Delivery doc. type ID",
	delivDocType__lbl: "Delivery doc. type",
	delivEventData__lbl: "Delivery date",
	delivTxTypeId__lbl: "Delivery transact. type ID",
	delivTxType__lbl: "Delivery transact. type",
	delivered__lbl: "Delivered",
	deliveryMethodId__lbl: "Delivery Method(ID)",
	deliveryMethod__lbl: "Delivery Method",
	deliveryNotes__lbl: "Delivery Notes",
	description__lbl: "Description",
	docDate__lbl: "Doc Date",
	docNo__lbl: "Doc No",
	docTypeId__lbl: "Doc Type(ID)",
	docType__lbl: "Doc Type",
	invDocTypeId__lbl: "Invoice type ID",
	invDocType__lbl: "Invoice type",
	inventoryId__lbl: "Inventory(ID)",
	inventory__lbl: "Inventory",
	invoiced__lbl: "Invoiced",
	paymentMethodId__lbl: "Payment Method(ID)",
	paymentMethod__lbl: "Payment Method",
	paymentTermId__lbl: "Payment Term(ID)",
	paymentTerm__lbl: "Payment Term",
	plannedDeliveryDate__lbl: "Planned Delivery Date",
	priceListId__lbl: "Price List(ID)",
	priceList__lbl: "Price List",
	shipToCode__lbl: "Ship To Code",
	shipToContactId__lbl: "Ship To Contact(ID)",
	shipToContact__lbl: "Ship To Contact",
	shipToId__lbl: "Ship To(ID)",
	shipToLocationId__lbl: "Ship To Location(ID)",
	shipToLocation__lbl: "Ship To Location",
	shipToUuid__lbl: "Ship To(UUID)",
	shipTo__lbl: "Ship To",
	supplierId__lbl: "Supplier(ID)",
	supplier__lbl: "Supplier",
	totalAmount__lbl: "Total Amount",
	totalNetAmount__lbl: "Total Net Amount",
	totalTaxAmount__lbl: "Total Tax Amount"
});
