Ext.define("net.nan21.dnet.module.md.bp.ds.model.BpAccountDs$Trl", {
	
	analiticSegment__lbl: "Segment analitic",
	businessPartnerId__lbl: "Terţ(ID)",
	businessPartner__lbl: "Terţ",
	custAnaliticSegment__lbl: "Segm. analit. client",
	customerCreditLimit__lbl: "Limită credit c.",
	customerGroupId__lbl: "Grup client(ID)",
	customerGroup__lbl: "Grup client",
	customerPaymentMethodId__lbl: "Metodă plată c.(ID)",
	customerPaymentMethod__lbl: "Metodă plată c.",
	customerPaymentTermId__lbl: "Termeni plată c.(ID)",
	customerPaymentTerm__lbl: "Termeni plată c.",
	customer__lbl: "Client",
	orgId__lbl: "Organizaţie(ID)",
	org__lbl: "Organizaţie",
	vendAnaliticSegment__lbl: "Segm. analit. furn.",
	vendorCreditLimit__lbl: "Limită credit f.",
	vendorGroupId__lbl: "Grup furnizor(ID)",
	vendorGroup__lbl: "Grup furnizor",
	vendorPaymentMethodId__lbl: "Metodă plată f.(ID)",
	vendorPaymentMethod__lbl: "Metodă plată f.",
	vendorPaymentTermId__lbl: "Termeni plată f.(ID)",
	vendorPaymentTerm__lbl: "Termeni plată f.",
	vendor__lbl: "Furnizor"
});
