Ext.define("net.nan21.dnet.module.md.activity.ds.model.MyCalendarEventDs$Trl", {
	
	allDay__lbl: "Toată ziua",
	bpartnerCode__lbl: "Terţ",
	bpartnerId__lbl: "Terţ(ID)",
	clientId__lbl: "Client Id",
	contactId__lbl: "Contact(ID)",
	contact__lbl: "Contact",
	createdBy__lbl: "Created By",
	dueDate__lbl: "Planificat la",
	endDate__lbl: "Până la",
	eventType__lbl: "Tip",
	id__lbl: "Id",
	location__lbl: "Locaţie",
	notes__lbl: "Notes",
	priorityId__lbl: "Prioritate(ID)",
	priorityName__lbl: "Prioritate",
	reminder__lbl: "Notificare",
	startDate__lbl: "De la",
	statusId__lbl: "Stare(ID)",
	statusName__lbl: "Stare",
	subject__lbl: "Titlu",
	targetId__lbl: "Target Id",
	targetType__lbl: "Target Type",
	url__lbl: "URL"
});
