Ext.define("net.nan21.dnet.module.md.mm.prod.ds.model.ProductDs$Trl", {
	
	attributeSetId__lbl: "Grup atribute(ID)",
	attributeSet__lbl: "Grup atribute",
	businessObject__lbl: "Business Object",
	className__lbl: "Class Name",
	defaultUomCode__lbl: "UM",
	defaultUomId__lbl: "UM(ID)",
	description__lbl: "Description",
	dimDepth__lbl: "Lăţime",
	dimHeight__lbl: "Înălţime",
	dimUomCode__lbl: "UM dimensiuni",
	dimUomId__lbl: "UM dimensiuni(ID)",
	dimWidth__lbl: "Lungime",
	iconUrl__lbl: "URL icoană",
	imageUrl__lbl: "URL imagine",
	manufacturerCode__lbl: "Producător",
	manufacturerId__lbl: "Producător(ID)",
	manufacturerProductNo__lbl: "Cod produc.",
	productCategoryId__lbl: "Categorie ID",
	productCategory__lbl: "Categorie",
	purchase__lbl: "Cumpărare",
	sale__lbl: "Vânzare",
	showInCatalog__lbl: "În catalog",
	storable__lbl: "Stocabil",
	volumeUomCode__lbl: "UM Volum",
	volumeUomId__lbl: "UM Volum(ID)",
	volume__lbl: "Volum",
	weightUomCode__lbl: "UM masă",
	weightUomId__lbl: "UM masă(ID)",
	weight__lbl: "Masă"
});
