Ext.define("net.nan21.dnet.module.md.tx.acc.ds.model.AccDocDs$Trl", {
	
	accSchemaId__lbl: "Acc Schema(ID)",
	accSchema__lbl: "Acc Schema",
	bpartnerId__lbl: "Bpartner(ID)",
	bpartner__lbl: "Bpartner",
	crAmount__lbl: "Cr Amount",
	dbAmount__lbl: "Db Amount",
	difference__lbl: "Difference",
	docAmount__lbl: "Doc Amount",
	docCurrencyId__lbl: "Doc Currency(ID)",
	docCurrency__lbl: "Doc Currency",
	docDate__lbl: "Doc Date",
	docNetAmount__lbl: "Doc Net Amount",
	docNo__lbl: "Doc No",
	docTaxAmount__lbl: "Doc Tax Amount",
	docTypeId__lbl: "Doc Type(ID)",
	docType__lbl: "Doc Type",
	journalId__lbl: "Journal(ID)",
	journal__lbl: "Journal",
	orgId__lbl: "Org(ID)",
	org__lbl: "Org",
	periodId__lbl: "Period(ID)",
	period__lbl: "Period",
	posted__lbl: "Posted"
});
