Ext.define("net.nan21.dnet.module.md.bp.ds.model.BpAccountDs$Trl", {
	
	analiticSegment__lbl: "Analitic Segment",
	businessPartnerId__lbl: "Business Partner(ID)",
	businessPartner__lbl: "Business Partner",
	custAnaliticSegment__lbl: "Cust Analitic Segment",
	customerCreditLimit__lbl: "Customer Credit Limit",
	customerGroupId__lbl: "Customer Group(ID)",
	customerGroup__lbl: "Customer Group",
	customerPaymentMethodId__lbl: "Customer Payment Method(ID)",
	customerPaymentMethod__lbl: "Customer Payment Method",
	customerPaymentTermId__lbl: "Customer Payment Term(ID)",
	customerPaymentTerm__lbl: "Customer Payment Term",
	customer__lbl: "Customer",
	orgId__lbl: "Org(ID)",
	org__lbl: "Org",
	vendAnaliticSegment__lbl: "Vend Analitic Segment",
	vendorCreditLimit__lbl: "Vendor Credit Limit",
	vendorGroupId__lbl: "Vendor group(ID)",
	vendorGroup__lbl: "Vendor group",
	vendorPaymentMethodId__lbl: "Vendor Payment Method(ID)",
	vendorPaymentMethod__lbl: "Vendor Payment Method",
	vendorPaymentTermId__lbl: "Vendor Payment Term(ID)",
	vendorPaymentTerm__lbl: "Vendor Payment Term",
	vendor__lbl: "Vendor"
});
