Ext.define("net.nan21.dnet.module.md.activity.ds.model.MyCalendarEventDs$Trl", {
	
	allDay__lbl: "All Day",
	bpartnerCode__lbl: "Business partner",
	bpartnerId__lbl: "Business partner(ID)",
	clientId__lbl: "Client Id",
	contactId__lbl: "Contact(ID)",
	contact__lbl: "Contact",
	createdBy__lbl: "Created By",
	dueDate__lbl: "Due Date",
	endDate__lbl: "End Date",
	eventType__lbl: "Type",
	id__lbl: "Id",
	location__lbl: "Location",
	notes__lbl: "Notes",
	priorityId__lbl: "Priority(ID)",
	priorityName__lbl: "Priority",
	reminder__lbl: "Reminder",
	startDate__lbl: "Start Date",
	statusId__lbl: "Status(ID)",
	statusName__lbl: "Status",
	subject__lbl: "Subject",
	targetId__lbl: "Target Id",
	targetType__lbl: "Target Type",
	url__lbl: "Url"
});
