Ext.define("net.nan21.dnet.module.md.mm.prod.ds.model.ProductDs$Trl", {
	
	attributeSetId__lbl: "Attribute Set(ID)",
	attributeSet__lbl: "Attribute Set",
	businessObject__lbl: "Business Object",
	className__lbl: "Class Name",
	defaultUomCode__lbl: "UoM",
	defaultUomId__lbl: "Default Uom(ID)",
	description__lbl: "Description",
	dimDepth__lbl: "Depth",
	dimHeight__lbl: "Height",
	dimUomCode__lbl: "Dim. UoM",
	dimUomId__lbl: "Dim Uom(ID)",
	dimWidth__lbl: "Width",
	iconUrl__lbl: "Icon Url",
	imageUrl__lbl: "Image Url",
	manufacturerCode__lbl: "Manufacturer",
	manufacturerId__lbl: "Manufacturer(ID)",
	manufacturerProductNo__lbl: "Manufact. prod. code",
	productCategoryId__lbl: "Product Category Id",
	productCategory__lbl: "Product Category",
	purchase__lbl: "Purchase",
	sale__lbl: "Sale",
	showInCatalog__lbl: "Show In Catalog",
	storable__lbl: "Storable",
	volumeUomCode__lbl: "Volume UoM",
	volumeUomId__lbl: "Volume Uom(ID)",
	volume__lbl: "Volume",
	weightUomCode__lbl: "Weight UoM",
	weightUomId__lbl: "Weight Uom(ID)",
	weight__lbl: "Weight"
});
