Ext.define("net.nan21.dnet.module.pj.md.ds.model.IssueDs$Trl", {
	
	affectedComponentId__lbl: "Affected Component Id",
	affectedComponent__lbl: "Affected Component",
	affectedVersionId__lbl: "Affected Version Id",
	affectedVersion__lbl: "Affected Version",
	assigneeId__lbl: "Assignee(ID)",
	assigneeRoleId__lbl: "Assignee Role(ID)",
	assigneeRole__lbl: "Assignee Role",
	assignee__lbl: "Assignee",
	businessObject__lbl: "Business Object",
	businessValue__lbl: "Business Value",
	clarity__lbl: "Clarity",
	code__lbl: "Code",
	description__lbl: "Description",
	dueDate__lbl: "Due Date",
	estimatedEffort__lbl: "Estimated Effort",
	fixedInVersionId__lbl: "Fixed In Version(ID)",
	fixedInVersion__lbl: "Fixed In Version",
	priorityId__lbl: "Priority(ID)",
	priority__lbl: "Priority",
	projectId__lbl: "Project(ID)",
	projectName__lbl: "Project Name",
	project__lbl: "Project",
	reportedVersionId__lbl: "Reported Version(ID)",
	reportedVersion__lbl: "Reported Version",
	resolutionDate__lbl: "Resolution Date",
	resolutionId__lbl: "Resolution(ID)",
	resolution__lbl: "Resolution",
	severityId__lbl: "Severity(ID)",
	severity__lbl: "Severity",
	statusId__lbl: "Status(ID)",
	status__lbl: "Status",
	summary__lbl: "Summary",
	targetVersionId__lbl: "Target Version(ID)",
	targetVersion__lbl: "Target Version",
	typeId__lbl: "Type(ID)",
	type__lbl: "Type"
});
