Ext.define("net.nan21.dnet.module.pj.md.ds.model.IssueTaskDs$Trl", {
	
	assigneeId__lbl: "Assignee(ID)",
	assignee__lbl: "Assignee",
	code__lbl: "Code",
	description__lbl: "Description",
	issueBusinessObject__lbl: "Issue Business Object",
	issueClassName__lbl: "Issue Class Name",
	issueId__lbl: "Issue(ID)",
	issuePriorityId__lbl: "Issue Priority(ID)",
	issuePrioritySequenceNo__lbl: "Issue Priority Sequence No",
	issuePriority__lbl: "Issue Priority",
	issueSeverityId__lbl: "Issue Severity(ID)",
	issueSeverity__lbl: "Issue Severity",
	issueStatusId__lbl: "Issue Status(ID)",
	issueStatus__lbl: "Issue Status",
	issueSummary__lbl: "Issue Summary",
	issueTypeId__lbl: "Issue Type(ID)",
	issueType__lbl: "Issue Type",
	issueUuId__lbl: "Issue Uu Id",
	issue__lbl: "Issue",
	projectId__lbl: "Project(ID)",
	projectName__lbl: "Project Name",
	project__lbl: "Project",
	statusId__lbl: "Status(ID)",
	status__lbl: "Status",
	typeId__lbl: "Type(ID)",
	type__lbl: "Type"
});
