Ext.define("net.nan21.dnet.module.sd.opportunity.ds.model.OpportunityDs$Trl", {
	
	accountId__lbl: "Terţ(ID)",
	account__lbl: "Terţ",
	amount__lbl: "Valoare",
	assignedToId__lbl: "Alocat la(ID)",
	assignedTo__lbl: "Alocat la",
	businessObject__lbl: "Business Object",
	campaign__lbl: "Campanie",
	className__lbl: "Class Name",
	closeDate__lbl: "Dată",
	currencyId__lbl: "Monedă(ID)",
	currency__lbl: "Monedă",
	leadSourceId__lbl: "Sursa(ID)",
	leadSource__lbl: "Sursa",
	priorityId__lbl: "Prioritate(ID)",
	priority__lbl: "Prioritate",
	probability__lbl: "Probabilitate",
	resultNote__lbl: "Explicatie rezultat",
	resultReasonId__lbl: "Rezultat(ID)",
	resultReason__lbl: "Rezultat",
	salesStageId__lbl: "Stadiu vânzari(ID)",
	salesStage__lbl: "Stadiu vânzari",
	statusId__lbl: "Stare(ID)",
	status__lbl: "Stare"
});
