Ext.define("net.nan21.dnet.module.sd.invoice.ds.model.SalesInvoiceItemOverviewDs$Trl", {
	
	confirmed__lbl: "Confirmat",
	currencyId__lbl: "Monedă(ID)",
	currency__lbl: "Monedă",
	customerCode__lbl: "Terţ",
	customerId__lbl: "Terţ(ID)",
	customerName__lbl: "Terţ",
	description__lbl: "Description",
	docCode__lbl: "Factură",
	docDate__lbl: "Dată doc.",
	docId__lbl: "Factură(ID)",
	docNo__lbl: "Nr doc",
	docTypeId__lbl: "Tip doc(ID)",
	docType__lbl: "Tip doc",
	lineAmount__lbl: "Valoare",
	netAmount__lbl: "Valoare netă",
	posted__lbl: "Inregistrat",
	productCode__lbl: "Articol",
	productId__lbl: "Articol(ID)",
	productName__lbl: "Articol",
	quantity__lbl: "Cantitate",
	supplierCode__lbl: "Org. furnizor",
	supplierId__lbl: "Org. furnizor(ID)",
	supplierName__lbl: "Org. furnizor",
	taxAmount__lbl: "Valoare taxe",
	taxId__lbl: "Taxă(ID)",
	tax__lbl: "Taxă",
	unitPrice__lbl: "Preţ unitar",
	uomCode__lbl: "UM",
	uomId__lbl: "UM(ID)"
});
