Ext.define("net.nan21.dnet.module.sd.order.ds.model.SalesDeliveryDs$Trl", {
	
	carrierId__lbl: "Gestiune destinaţie(ID)",
	carrier__lbl: "Gestiune destinaţie",
	code__lbl: "Cod",
	confirmed__lbl: "Confirmat",
	customerCode__lbl: "Client",
	customerId__lbl: "Client(ID)",
	customer__lbl: "Client",
	deliveryContactId__lbl: "Delegat livrare(ID)",
	deliveryContact__lbl: "Delegat livrare",
	deliveryLocationId__lbl: "Adresă livrare(ID)",
	deliveryLocation__lbl: "",
	docDate__lbl: "Dată doc.",
	docNo__lbl: "Nr doc",
	eventDate__lbl: "Dată eveniment",
	posted__lbl: "Inregistrat",
	salesOrderId__lbl: "Comandă client(ID)",
	salesOrderUuid__lbl: "",
	salesOrder__lbl: "Comandă client",
	transactionTypeId__lbl: "Tip(ID)",
	transactionType__lbl: "Tip",
	warehouseId__lbl: "Gestiune sursă(ID)",
	warehouse__lbl: "Gestiune sursă"
});
