Ext.define("net.nan21.dnet.module.sd.invoice.ds.model.SalesInvoiceDs$Trl", {
	
	billToContactId__lbl: "Delegat(ID)",
	billToContact__lbl: "Delegat",
	billToLocationId__lbl: "Adresă facturare(ID)",
	billToLocation__lbl: "",
	businessObject__lbl: "Business Object",
	className__lbl: "Class Name",
	code__lbl: "Cod",
	confirmed__lbl: "Confirmat",
	currencyId__lbl: "Monedă(ID)",
	currency__lbl: "Monedă",
	customerCode__lbl: "Terţ",
	customerId__lbl: "Terţ(ID)",
	customerUuid__lbl: "",
	customer__lbl: "Terţ",
	description__lbl: "Description",
	docDate__lbl: "Dată doc.",
	docNo__lbl: "Nr doc",
	docTypeId__lbl: "Tip doc(ID)",
	docType__lbl: "Tip doc",
	paymentMethodId__lbl: "Mod plată(ID)",
	paymentMethod__lbl: "Mod plată",
	paymentTermId__lbl: "Termen plată(ID)",
	paymentTerm__lbl: "Termen plată",
	posted__lbl: "Inregistrat",
	priceListId__lbl: "Listă preţ(ID)",
	priceList__lbl: "Listă preţ",
	salesOrderCode__lbl: "Comandă client",
	salesOrderId__lbl: "Comandă client(ID)",
	supplierId__lbl: "Org. furnizor(ID)",
	supplier__lbl: "Org. furnizor",
	totalAmount__lbl: "Total",
	totalNetAmount__lbl: "Total Net",
	totalTaxAmount__lbl: "Total TVA"
});
