Ext.define("net.nan21.dnet.module.sd.order.ds.model.SalesOrderDs$Trl", {
	
	billToCode__lbl: "Terţ factură",
	billToContactId__lbl: "Delegat factură(ID)",
	billToContact__lbl: "Delegat factură",
	billToId__lbl: "Terţ factură(ID)",
	billToLocationId__lbl: "Adresă factură(ID)",
	billToLocation__lbl: "",
	billToUuid__lbl: "",
	billTo__lbl: "Terţ factură",
	businessObject__lbl: "Business Object",
	carrierId__lbl: "null(ID)",
	carrier__lbl: "",
	className__lbl: "Class Name",
	code__lbl: "Cod",
	confirmed__lbl: "Confirmat",
	currencyId__lbl: "Monedă(ID)",
	currency__lbl: "Monedă",
	customerCode__lbl: "Terţ",
	customerId__lbl: "Terţ(ID)",
	customerUuid__lbl: "",
	customer__lbl: "Terţ",
	delivDocTypeId__lbl: "ID tip doc livrare",
	delivDocType__lbl: "Tip doc livrare",
	delivEventData__lbl: "Data livarare",
	delivTxTypeId__lbl: "ID tip tranzactie livrare",
	delivTxType__lbl: "ID tip tranzactie livrare",
	delivered__lbl: "Livrat",
	deliveryMethodId__lbl: "Mod livrare(ID)",
	deliveryMethod__lbl: "Mod livrare",
	deliveryNotes__lbl: "Note livrare",
	description__lbl: "Description",
	docDate__lbl: "Dată doc.",
	docNo__lbl: "Nr doc",
	docTypeId__lbl: "Tip doc(ID)",
	docType__lbl: "Tip doc",
	invDocTypeId__lbl: "ID tip factura",
	invDocType__lbl: "Tip factura",
	inventoryId__lbl: "Gestiune(ID)",
	inventory__lbl: "Gestiune",
	invoiced__lbl: "Facturat",
	paymentMethodId__lbl: "Mod plată(ID)",
	paymentMethod__lbl: "Mod plată",
	paymentTermId__lbl: "Termen plată(ID)",
	paymentTerm__lbl: "Termen plată",
	plannedDeliveryDate__lbl: "Dată livrare planif.",
	priceListId__lbl: "Listă preţ(ID)",
	priceList__lbl: "Listă preţ",
	shipToCode__lbl: "Terţ livrare",
	shipToContactId__lbl: "Delegat livrare(ID)",
	shipToContact__lbl: "Delegat livrare",
	shipToId__lbl: "Terţ livrare(ID)",
	shipToLocationId__lbl: "Adresă livrare(ID)",
	shipToLocation__lbl: "",
	shipToUuid__lbl: "",
	shipTo__lbl: "Terţ livrare",
	supplierId__lbl: "Org. furnizor(ID)",
	supplier__lbl: "Org. furnizor",
	totalAmount__lbl: "Total",
	totalNetAmount__lbl: "Total Net",
	totalTaxAmount__lbl: "Total taxe"
});
