Ext.define("net.nan21.dnet.module.sc.invoice.ds.model.PurchaseTxAmountPaymentProposalDs$Trl", {
	
	bpartnerId__lbl: "Tert(ID)",
	businessPartner__lbl: "Beneficiar",
	currencyId__lbl: "null(ID)",
	currency__lbl: "",
	currentPayment__lbl: "Valoare",
	dueAmount__lbl: "Valoare",
	dueDate__lbl: "Due Date",
	invoiceCode__lbl: "",
	invoiceDocDate__lbl: "Dată doc.",
	invoiceDocNo__lbl: "Nr doc",
	invoiceId__lbl: "null(ID)",
	orderCode__lbl: "",
	orderDocDate__lbl: "Dată doc.",
	orderDocNo__lbl: "Nr doc",
	orderId__lbl: "null(ID)",
	orgId__lbl: "Organizatie(ID)",
	outstandingAmount__lbl: "Valoare",
	payedAmount__lbl: "Valoare",
	paymentCurrency__lbl: "Monedă",
	paymentId__lbl: "",
	paymentMethodId__lbl: "null(ID)",
	paymentMethod__lbl: "",
	receivedAmount__lbl: "Suma plătită",
	remainingAmount__lbl: "Valoare",
	unAllocatedAmount__lbl: "Suma nealocată"
});
