Ext.define("net.nan21.dnet.module.sc.order.ds.model.PurchaseOrderDs$Trl", {
	
	businessObject__lbl: "Business Object",
	className__lbl: "Class Name",
	code__lbl: "Cod",
	confirmed__lbl: "Confirmat",
	currencyId__lbl: "Monedă(ID)",
	currency__lbl: "Monedă",
	customerId__lbl: "Cumpărător(ID)",
	customer__lbl: "Cumpărător",
	deliveryMethodId__lbl: "Mod livrare(ID)",
	deliveryMethod__lbl: "Mod livrare",
	deliveryNotes__lbl: "Note livrare",
	description__lbl: "Description",
	docDate__lbl: "Dată doc.",
	docNo__lbl: "Nr doc",
	docTypeId__lbl: "Tip doc(ID)",
	docType__lbl: "Tip doc",
	inventoryId__lbl: "Gestiune(ID)",
	inventory__lbl: "Gestiune",
	paymentMethodId__lbl: "Mod plată(ID)",
	paymentMethod__lbl: "Mod plată",
	paymentTermId__lbl: "Termen plată(ID)",
	paymentTerm__lbl: "Termen plată",
	plannedDeliveryDate__lbl: "Dată livrare planif.",
	priceListId__lbl: "Listă preţ(ID)",
	priceList__lbl: "Listă preţ",
	supplierCode__lbl: "Furnizor",
	supplierId__lbl: "Furnizor(ID)",
	supplierUuid__lbl: "",
	supplier__lbl: "Furnizor",
	totalAmount__lbl: "Total",
	totalNetAmount__lbl: "Total Net",
	totalTaxAmount__lbl: "Total taxe"
});
