Ext.define("net.nan21.dnet.module.sc.invoice.ds.model.PurchaseInvoiceItemOverviewDs$Trl", {
	
	confirmed__lbl: "Confirmat",
	currencyId__lbl: "Monedă(ID)",
	currency__lbl: "Monedă",
	customerCode__lbl: "Cumpărător",
	customerId__lbl: "Cumpărător(ID)",
	customerName__lbl: "Cumpărător",
	description__lbl: "Description",
	docCode__lbl: "",
	docDate__lbl: "Dată doc.",
	docId__lbl: "null(ID)",
	docNo__lbl: "Nr doc",
	docTypeId__lbl: "Tip doc(ID)",
	docType__lbl: "Tip doc",
	entryMode__lbl: "Entry Mode",
	lineAmount__lbl: "Valoare",
	netAmount__lbl: "Valoare netă",
	posted__lbl: "Inregistrat",
	productCode__lbl: "Articol",
	productId__lbl: "Articol(ID)",
	productName__lbl: "Articol",
	quantity__lbl: "Cantitate",
	supplierCode__lbl: "Furnizor",
	supplierId__lbl: "Furnizor(ID)",
	supplierName__lbl: "Furnizor",
	taxAmount__lbl: "Valoare taxe",
	taxId__lbl: "Taxă(ID)",
	tax__lbl: "Taxă",
	unitPrice__lbl: "Preţ unitar",
	uomCode__lbl: "UM",
	uomId__lbl: "UM(ID)"
});
