Ext.define("net.nan21.dnet.module.sc.invoice.ds.model.PurchaseInvoiceDs$Trl", {
	
	businessObject__lbl: "Business Object",
	className__lbl: "Class Name",
	code__lbl: "Cod",
	confirmed__lbl: "Confirmat",
	currencyId__lbl: "Monedă(ID)",
	currency__lbl: "Monedă",
	customerId__lbl: "Cumpărător(ID)",
	customer__lbl: "Cumpărător",
	description__lbl: "Description",
	docDate__lbl: "Dată doc.",
	docNo__lbl: "Nr doc",
	docTypeId__lbl: "Tip doc(ID)",
	docType__lbl: "Tip doc",
	fromAccountId__lbl: "Din cont(ID)",
	fromAccount__lbl: "Din cont",
	paymentMethodId__lbl: "Mod plată(ID)",
	paymentMethodType__lbl: "Tip",
	paymentMethod__lbl: "Mod plată",
	paymentTermId__lbl: "Termen plată(ID)",
	paymentTerm__lbl: "Termen plată",
	posted__lbl: "Inregistrat",
	purchaseOrderId__lbl: "null(ID)",
	selfPayed__lbl: "Self Payed",
	supplierCode__lbl: "Furnizor",
	supplierId__lbl: "Furnizor(ID)",
	supplierUuid__lbl: "",
	supplier__lbl: "Furnizor",
	totalAmount__lbl: "Total",
	totalNetAmount__lbl: "Total Net",
	totalTaxAmount__lbl: "Total TVA"
});
