Ext.define("net.nan21.dnet.module.sc.invoice.ds.model.PurchaseInvoiceDs$Trl", {
	
	businessObject__lbl: "Business Object",
	className__lbl: "Class Name",
	code__lbl: "Code",
	confirmed__lbl: "Confirmed",
	currencyId__lbl: "Currency(ID)",
	currency__lbl: "Currency",
	customerId__lbl: "Customer(ID)",
	customer__lbl: "Customer",
	description__lbl: "Description",
	docDate__lbl: "Doc Date",
	docNo__lbl: "Doc No",
	docTypeId__lbl: "Doc Type(ID)",
	docType__lbl: "Doc Type",
	fromAccountId__lbl: "From Account(ID)",
	fromAccount__lbl: "From Account",
	paymentMethodId__lbl: "Payment Method(ID)",
	paymentMethodType__lbl: "Payment Method Type",
	paymentMethod__lbl: "Payment Method",
	paymentTermId__lbl: "Payment Term(ID)",
	paymentTerm__lbl: "Payment Term",
	posted__lbl: "Posted",
	purchaseOrderId__lbl: "Purchase Order(ID)",
	selfPayed__lbl: "Self Payed",
	supplierCode__lbl: "Supplier Code",
	supplierId__lbl: "Supplier(ID)",
	supplierUuid__lbl: "Supplier(UUID)",
	supplier__lbl: "Supplier",
	totalAmount__lbl: "Total Amount",
	totalNetAmount__lbl: "Total Net Amount",
	totalTaxAmount__lbl: "Total Tax Amount"
});
