Ext.define("net.nan21.dnet.module.sc.invoice.ds.model.PurchaseInvoiceItemOverviewDs$Trl", {
	
	confirmed__lbl: "Confirmed",
	currencyId__lbl: "Currency(ID)",
	currency__lbl: "Currency",
	customerCode__lbl: "Customer Code",
	customerId__lbl: "Customer(ID)",
	customerName__lbl: "Customer Name",
	description__lbl: "Description",
	docCode__lbl: "Doc Code",
	docDate__lbl: "Doc Date",
	docId__lbl: "Doc(ID)",
	docNo__lbl: "Doc No",
	docTypeId__lbl: "Doc Type(ID)",
	docType__lbl: "Doc Type",
	entryMode__lbl: "Entry Mode",
	lineAmount__lbl: "Line Amount",
	netAmount__lbl: "Net Amount",
	posted__lbl: "Posted",
	productCode__lbl: "Product Code",
	productId__lbl: "Product(ID)",
	productName__lbl: "Product Name",
	quantity__lbl: "Quantity",
	supplierCode__lbl: "Supplier Code",
	supplierId__lbl: "Supplier(ID)",
	supplierName__lbl: "Supplier Name",
	taxAmount__lbl: "Tax Amount",
	taxId__lbl: "Tax(ID)",
	tax__lbl: "Tax",
	unitPrice__lbl: "Unit Price",
	uomCode__lbl: "Uom Code",
	uomId__lbl: "Uom(ID)"
});
