Ext.define("net.nan21.dnet.module.sc.invoice.ds.model.PurchaseTxAmountPaymentProposalDs$Trl", {
	
	bpartnerId__lbl: "Bpartner(ID)",
	businessPartner__lbl: "Payed to",
	currency__lbl: "Currency",
	currentPayment__lbl: "Current Payment",
	dueAmount__lbl: "Due Amount",
	dueDate__lbl: "Due Date",
	invoiceCode__lbl: "Invoice Code",
	invoiceDocDate__lbl: "Invoice Doc Date",
	invoiceDocNo__lbl: "Invoice Doc No",
	invoiceId__lbl: "Invoice(ID)",
	orderCode__lbl: "Order Code",
	orderDocDate__lbl: "Order Doc Date",
	orderDocNo__lbl: "Order Doc No",
	orderId__lbl: "Order(ID)",
	orgId__lbl: "Org(ID)",
	outstandingAmount__lbl: "Outstanding Amount",
	payedAmount__lbl: "Payed Amount",
	paymentId__lbl: "",
	paymentMethodId__lbl: "Payment Method(ID)",
	paymentMethod__lbl: "Payment Method",
	receivedAmount__lbl: "Payed amount",
	remainingAmount__lbl: "Remaining Amount",
	unAllocatedAmount__lbl: "Unused amount"
});
