Ext.define("net.nan21.dnet.module.sc.order.ds.model.PurchaseOrderDs$Trl", {
	
	businessObject__lbl: "Business Object",
	className__lbl: "Class Name",
	code__lbl: "Code",
	confirmed__lbl: "Confirmed",
	currencyId__lbl: "Currency(ID)",
	currency__lbl: "Currency",
	customerId__lbl: "Customer(ID)",
	customer__lbl: "Customer",
	deliveryMethodId__lbl: "Delivery Method(ID)",
	deliveryMethod__lbl: "Delivery Method",
	deliveryNotes__lbl: "Delivery Notes",
	description__lbl: "Description",
	docDate__lbl: "Doc Date",
	docNo__lbl: "Doc No",
	docTypeId__lbl: "Doc Type(ID)",
	docType__lbl: "Doc Type",
	inventoryId__lbl: "Inventory(ID)",
	inventory__lbl: "Inventory",
	paymentMethodId__lbl: "Payment Method(ID)",
	paymentMethod__lbl: "Payment Method",
	paymentTermId__lbl: "Payment Term(ID)",
	paymentTerm__lbl: "Payment Term",
	plannedDeliveryDate__lbl: "Planned Delivery Date",
	priceListId__lbl: "Price List(ID)",
	priceList__lbl: "Price List",
	supplierCode__lbl: "Supplier Code",
	supplierId__lbl: "Supplier(ID)",
	supplierUuid__lbl: "Supplier(UUID)",
	supplier__lbl: "Supplier",
	totalAmount__lbl: "Total Amount",
	totalNetAmount__lbl: "Total Net Amount",
	totalTaxAmount__lbl: "Total Tax Amount"
});
