Ext.define("net.nan21.dnet.module.sd.invoice.frame.SalesInvoice_UI$Trl", {
	/* view */
	accDocLineFilter__ttl: "Filter",
	accDocPanel__ttl: "Accounting",
	amountsPanel__ttl: "Payment info",
	atchEditList__ttl: "Attachments",
	invEditDetails__ttl: "Details",
	itemFilter__ttl: "Filter",
	itemTaxList__ttl: "Item taxes",
	linesPanel__ttl: "Items",
	notesPanel__ttl: "Notes",
	taxList__ttl: "Taxes",
	wdwCopyLines__ttl: "Copy lines from invoice",
	/* menu */
	tlbAccDocLineList__ttl: "Accounting",
	tlbAmountList__ttl: "Receivables",
	tlbInvEdit__ttl: "Sales invoice",
	tlbInvList__ttl: "Sales invoices",
	tlbItemEdit__ttl: "Item",
	tlbItemList__ttl: "Items",
	tlbPayedAmountList__ttl: "Payments",
	tlbTaxList__ttl: "Taxes",
	/* button */
	btnConfirmInvoice__ttl: "Confirm",
	btnConfirmInvoice__desc: "Confirm invoice.",
	btnDoCopyLines__ttl: "Execute",
	btnDoCopyLines__desc: "",
	btnPostInvoice__ttl: "Post",
	btnPostInvoice__desc: "Post invoice to accounting.",
	btnShowCopyLines__ttl: "Copy lines",
	btnShowCopyLines__desc: "Copy lines from invoice",
	btnShowOrder__ttl: "Show Order",
	btnShowOrder__desc: "Show the sales order linked to this invoice",
	btnShowPayment__ttl: "Show payment document",
	btnShowPayment__desc: "Show the payment document",
	btnUnConfirmInvoice__ttl: "Un-Confirm",
	btnUnConfirmInvoice__desc: "Un-Confirm invoice.",
	btnUnPostInvoice__ttl: "Un-Post",
	btnUnPostInvoice__desc: "Un-Post invoice from accounting.",
	btnUploadAttachment__ttl: "Upload...",
	btnUploadAttachment__desc: "Upload attachment file.",
	btnViewAttachment__ttl: "View",
	btnViewAttachment__desc: "View the selected attachment",
	
	title: "Sales invoice"
});
