Ext.define("net.nan21.dnet.module.sc.invoice.frame.PurchaseInvoice_UI$Trl", {
	/* view */
	accDocLineFilter__ttl: "Filtru",
	accDocPanel__ttl: "Contabilitate",
	amountsPanel__ttl: "Detalii plată",
	atchEditList__ttl: "Ataşamente",
	invEditDetails__ttl: "Detalii",
	itemFilter__ttl: "Filtru",
	itemTaxList__ttl: "Taxe linie factură",
	linesPanel__ttl: "Articole",
	notesPanel__ttl: "Note",
	taxList__ttl: "Taxe",
	wdwCopyLines__ttl: "Copiaza linii din factura",
	/* menu */
	tlbAccDocLineList__ttl: "Contabilitate",
	tlbAmountList__ttl: "Solduri de plătit",
	tlbInvEdit__ttl: "Factură furnizor",
	tlbInvList__ttl: "Facturi furnizor",
	tlbItemEdit__ttl: "Articol",
	tlbItemList__ttl: "Articole",
	tlbPayedAmountList__ttl: "Plăţi",
	tlbTaxList__ttl: "Taxe",
	/* button */
	btnConfirmInvoice__ttl: "Confirmă",
	btnConfirmInvoice__desc: "Confirmă factură",
	btnDoCopyLines__ttl: "Execută",
	btnDoCopyLines__desc: "",
	btnPostInvoice__ttl: "Inregistrează",
	btnPostInvoice__desc: "Inregistrează factură",
	btnShowCopyLines__ttl: "Copiază linii",
	btnShowCopyLines__desc: "Copiază linii din factură",
	btnShowPayment__ttl: "Arată document plată",
	btnShowPayment__desc: "",
	btnUnConfirmInvoice__ttl: "De-Confirmă",
	btnUnConfirmInvoice__desc: "De-confirmă factură",
	btnUnPostInvoice__ttl: "De-Inregistrează",
	btnUnPostInvoice__desc: "De-Inregistrează factură",
	btnUploadAttachment__ttl: "Upload...",
	btnUploadAttachment__desc: "Upload ataşament",
	btnViewAttachment__ttl: "Deschide",
	btnViewAttachment__desc: "Deschide ataşament",
	
	title: "Facturi furnizor"
});
