Ext.define("net.nan21.dnet.module.hr.employee.ds.model.EmployeeAssignmentDs$Trl", {
	
	assignToPosition__lbl: "Cu poziţie",
	baseSalary__lbl: "Salariu baza",
	className__lbl: "Class Name",
	employeeCode__lbl: "Angajat",
	employeeId__lbl: "Angajat(ID)",
	employerCode__lbl: "Angajator",
	employerId__lbl: "Angajator(ID)",
	firstName__lbl: "Prenume",
	gradeCode__lbl: "Grad",
	gradeId__lbl: "Grad(ID)",
	jobCode__lbl: "Funcţie",
	jobId__lbl: "Funcţie(ID)",
	jobName__lbl: "Funcţie",
	lastName__lbl: "Nume",
	middleName__lbl: "Prenume 2",
	name__lbl: "Angajat",
	orgId__lbl: "Organizaţie(ID)",
	org__lbl: "Organizaţie",
	payrollId__lbl: "Frecvenţă(ID)",
	payroll__lbl: "Frecvenţă",
	posOrgId__lbl: "Organizaţie(ID)",
	posOrg__lbl: "Organizaţie",
	positionCode__lbl: "Poziţie",
	positionId__lbl: "Poziţie(ID)",
	positionName__lbl: "Poziţie",
	typeId__lbl: "Tip(ID)",
	type__lbl: "Tip",
	validAt__lbl: "Valid la",
	validFrom__lbl: "De la",
	validTo__lbl: "Până la"
});
