Ext.define("net.nan21.dnet.module.hr.employee.ds.model.EmployeeAssignmentDs$Trl", {
	
	assignToPosition__lbl: "Assign To Position",
	baseSalary__lbl: "Base Salary",
	className__lbl: "Class Name",
	employeeCode__lbl: "Employee Code",
	employeeId__lbl: "Employee(ID)",
	employerCode__lbl: "Employer Code",
	employerId__lbl: "Employer(ID)",
	firstName__lbl: "First Name",
	gradeCode__lbl: "Grade Code",
	gradeId__lbl: "Grade(ID)",
	jobCode__lbl: "Job Code",
	jobId__lbl: "Job(ID)",
	jobName__lbl: "Job Name",
	lastName__lbl: "Last Name",
	middleName__lbl: "Middle Name",
	name__lbl: "Name",
	orgId__lbl: "Org(ID)",
	org__lbl: "Org",
	payrollId__lbl: "Payroll(ID)",
	payroll__lbl: "Payroll",
	posOrgId__lbl: "Pos Org(ID)",
	posOrg__lbl: "Pos Org",
	positionCode__lbl: "Position Code",
	positionId__lbl: "Position(ID)",
	positionName__lbl: "Position Name",
	typeId__lbl: "Type(ID)",
	type__lbl: "Type",
	validAt__lbl: "Valid At",
	validFrom__lbl: "Valid From",
	validTo__lbl: "Valid To"
});
