Ext.define("net.nan21.dnet.module.fi.asset.ds.model.AssetDs$Trl", {
	
	calculation__lbl: "Calcul",
	categoryId__lbl: "Categorie(ID)",
	category__lbl: "Categorie",
	currencyId__lbl: "Monedă(ID)",
	currency__lbl: "Monedă",
	deprecEndDate__lbl: "Sfarsit amortizare",
	deprecStartDate__lbl: "Inceput amortizare",
	depreciationAmount__lbl: "Valoare amortizare",
	initialDeprecAmount__lbl: "Amortizare iniţială",
	initialValue__lbl: "Valoare iniţială",
	method__lbl: "Metodă",
	orgId__lbl: "Unitate(ID)",
	org__lbl: "Unitate",
	periodPercenatge__lbl: "Procent/perioada",
	periodType__lbl: "Tip perioadă",
	periodValue__lbl: "Nr. perioade",
	productCode__lbl: "Articol",
	productId__lbl: "Articol(ID)",
	productName__lbl: "Articol",
	purchaseDate__lbl: "Dată achiziţie",
	residualValue__lbl: "Valoare reziduală",
	withDepreciation__lbl: "Cu amortizare"
});
