Ext.define("net.nan21.dnet.module.pj.md.ds.model.IssueDs$Trl", {
	
	affectedComponentId__lbl: "ID componenta afectata",
	affectedComponent__lbl: "Componenta afectata",
	affectedVersionId__lbl: "ID versiune afectata",
	affectedVersion__lbl: "Versiune afectata",
	assigneeId__lbl: "Alocat la(ID)",
	assigneeRoleId__lbl: "null(ID)",
	assigneeRole__lbl: "",
	assignee__lbl: "Alocat la",
	businessObject__lbl: "Business Object",
	businessValue__lbl: "Valoare adaugată",
	clarity__lbl: "Claritate",
	code__lbl: "Cod",
	description__lbl: "Descriere",
	dueDate__lbl: "Planificat la",
	estimatedEffort__lbl: "Efort estimat",
	fixedInVersionId__lbl: "Rezolvat în vers.(ID)",
	fixedInVersion__lbl: "Rezolvat în vers.",
	priorityId__lbl: "Prioritate(ID)",
	priority__lbl: "Prioritate",
	projectId__lbl: "Proiect(ID)",
	projectName__lbl: "Proiect",
	project__lbl: "Proiect",
	reportedVersionId__lbl: "Reclamat în vers.(ID)",
	reportedVersion__lbl: "Reclamat în vers.",
	resolutionDate__lbl: "Rezolvat la",
	resolutionId__lbl: "Rezolvare(ID)",
	resolution__lbl: "Rezolvare",
	severityId__lbl: "Gravitate(ID)",
	severity__lbl: "Gravitate",
	statusId__lbl: "Stare(ID)",
	status__lbl: "Stare",
	summary__lbl: "Subiect",
	targetVersionId__lbl: "Planificat ptr. vers.(ID)",
	targetVersion__lbl: "Planificat ptr. vers.",
	typeId__lbl: "Tip(ID)",
	type__lbl: "Tip"
});
