Ext.define("net.nan21.dnet.module.pj.md.ds.model.IssueTaskDs$Trl", {
	
	assigneeId__lbl: "Alocat(ID)",
	assignee__lbl: "Alocat la",
	code__lbl: "Cod",
	description__lbl: "Descriere",
	issueBusinessObject__lbl: "",
	issueClassName__lbl: "",
	issueId__lbl: "Incident(ID)",
	issuePriorityId__lbl: "Prioritate(ID)",
	issuePrioritySequenceNo__lbl: "Secvenţă",
	issuePriority__lbl: "Prioritate",
	issueSeverityId__lbl: "Gravitate(ID)",
	issueSeverity__lbl: "Gravitate",
	issueStatusId__lbl: "Stare(ID)",
	issueStatus__lbl: "Stare",
	issueSummary__lbl: "Subiect",
	issueTypeId__lbl: "Tip(ID)",
	issueType__lbl: "Tip",
	issueUuId__lbl: "",
	issue__lbl: "Incident",
	projectId__lbl: "Proiect(ID)",
	projectName__lbl: "Proiect",
	project__lbl: "Proiect",
	statusId__lbl: "Stare(ID)",
	status__lbl: "Stare",
	typeId__lbl: "Tip(ID)",
	type__lbl: "Tip"
});
